name: Unpublish

on:
  workflow_dispatch:
    inputs:
      version: 
        description: "Version to unpublish"
        required: true
        default: ""

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - run: npm unpublish wdio-slack-report-service@${{ github.event.inputs.version }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
